# -*- coding: utf-8 -*-
"""faceRecognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zzTrxonRU6O7aF8VpNv3Wwx2M1Ds2UFg
"""

from google.colab import drive
drive.mount('/content/drive')

cd'drive/My Drive'

ls

import cv2
from keras.models import load_model
import numpy as np
import glob
import os
import matplotlib.pyplot as plt
from PIL import Image

i=0
namex=""
faceCascade=cv2.CascadeClassifier('reg_test/haarcascade_frontalface_default.xml')
font = cv2.FONT_HERSHEY_SIMPLEX
model=load_model('face73.h5')
path="8 celebirity/test/"
dec={    0:"Kevin Hart"  ,
         1:"ben_afflek"    ,
         2:"dwayne_johnson",
         3:"elton_john"     ,
         4:"jerry_seinfeld", 
         5:"madonna"       , 
         6:"mindy_kaling"  , 
         7:"Ryan Reynolds" 
      }
people=["Kevin Hart" ,"ben_afflek" ,"dwayne_johnson" ,"elton_john" ,"jerry_seinfeld", "madonna" , "mindy_kaling", "Ryan Reynolds"]
top=0
the_right=0
for person in people:
  for filepath in glob.glob(path+person+"/*"):
    img = cv2.imread(filepath)
    faces = faceCascade.detectMultiScale(img, 1.1, 4)
    ind=0
    for (x, y, w, h) in faces:
        imgResults = img[y:y + h, x:x + w]
        imgResults = cv2.resize(imgResults, (224, 224))
        imgResults=imgResults/255.0
        imgResults = np.reshape(imgResults, (1, 224, 224, 3))

        pre = model.predict(imgResults)

        cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)
        result = np.where(pre[0] == max(pre[0]))# returns the index of the result / prediction
        Finel_result=dec[int(result[0])]
        if person==Finel_result:
          cv2.putText(img,str(Finel_result),(x,y),font, 1,(255,255,255),2)
          the_right+=1
        ind+=1
    top+=1
    plt.imshow(img)
    plt.show()
print("the totel number "+str(top))
print("the right ones",the_right)
print(100 * float(the_right)/float(top))